services:
  postgres:
    image: registry.disy.net/sandbox/postgis_geopixel:0.0.1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask-app:
    image: registry.disy.net/sandbox/flask_geopixel:0.0.1
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      FLASK_ENV: production
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5000
      FLASK_DEBUG: false
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      CADENZA_API_URL: http://host.docker.internal:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
  adminer:
    image: adminer
    ports:
     - 3000:8080
volumes:
  postgres_data: